[package]
name = "nautilus-rules"
readme = "README.md"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
description = "Reusable rule system components for NautilusTrader"
categories.workspace = true
keywords.workspace = true
documentation.workspace = true
repository.workspace = true
homepage.workspace = true

[lints]
workspace = true

[lib]
name = "nautilus_rules"
crate-type = ["rlib"]

[features]
default = []

[dependencies]
nautilus-common = { workspace = true }
nautilus-model = { workspace = true }
