/* Generated with cbindgen:0.29.2 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdint.h>
#include <Python.h>

/**
 * 系统中组件的状态。
 */
typedef enum ComponentState {
    /**
     * 当组件被实例化，但尚未准备好履行其规范时。
     */
    PRE_INITIALIZED = 0,
    /**
     * 当组件能够启动时。
     */
    READY = 1,
    /**
     * 当组件在 `start` 时执行其操作。
     */
    STARTING = 2,
    /**
     * 当组件正正常运行并能履行其规范时。
     */
    RUNNING = 3,
    /**
     * 当组件在 `stop` 时执行其操作。
     */
    STOPPING = 4,
    /**
     * 当组件已成功停止。
     */
    STOPPED = 5,
    /**
     * 当组件在初始启动后再次启动。
     */
    RESUMING = 6,
    /**
     * 当组件在 `reset` 时执行其操作。
     */
    RESETTING = 7,
    /**
     * 当组件在 `dispose` 时执行其操作。
     */
    DISPOSING = 8,
    /**
     * 当组件已成功关闭并释放了所有资源。
     */
    DISPOSED = 9,
    /**
     * 当组件在 `degrade` 时执行其操作。
     */
    DEGRADING = 10,
    /**
     * 当组件已成功降级，可能无法完全履行其规范。
     */
    DEGRADED = 11,
    /**
     * 当组件在 `fault` 时执行其操作。
     */
    FAULTING = 12,
    /**
     * 当组件因检测到故障而成功关闭。
     */
    FAULTED = 13,
} ComponentState;

/**
 * 系统中组件的触发条件。
 */
typedef enum ComponentTrigger {
    /**
     * 组件初始化的触发器。
     */
    INITIALIZE = 1,
    /**
     * 组件启动的触发器。
     */
    START = 2,
    /**
     * 组件成功启动时的触发器。
     */
    START_COMPLETED = 3,
    /**
     * 组件停止的触发器。
     */
    STOP = 4,
    /**
     * 组件成功停止时的触发器。
     */
    STOP_COMPLETED = 5,
    /**
     * 组件恢复（停止后）的触发器。
     */
    RESUME_TRIGGER = 6,
    /**
     * 组件成功恢复时的触发器。
     */
    RESUME_COMPLETED = 7,
    /**
     * 组件重置的触发器。
     */
    RESET = 8,
    /**
     * 组件成功重置时的触发器。
     */
    RESET_COMPLETED = 9,
    /**
     * 组件销毁并释放资源的触发器。
     */
    DISPOSE = 10,
    /**
     * 组件成功销毁时的触发器。
     */
    DISPOSE_COMPLETED = 11,
    /**
     * 组件降级的触发器。
     */
    DEGRADE = 12,
    /**
     * 组件成功降级时的触发器。
     */
    DEGRADE_COMPLETED = 13,
    /**
     * 组件故障的触发器。
     */
    FAULT = 14,
    /**
     * 组件成功进入故障状态时的触发器。
     */
    FAULT_COMPLETED = 15,
} ComponentTrigger;

/**
 * 日志消息的日志级别。
 */
typedef enum LogLevel {
    /**
     * **OFF** 日志级别。低于所有其他日志级别（关闭）。
     */
    OFF = 0,
    /**
     * **TRACE** 日志级别。仅在 Rust 的调试/开发构建中可用。
     */
    TRACE = 1,
    /**
     * **DEBUG** 日志级别。
     */
    DEBUG = 2,
    /**
     * **INFO** 日志级别。
     */
    INFO = 3,
    /**
     * **WARNING** 日志级别。
     */
    WARNING = 4,
    /**
     * **ERROR** 日志级别。
     */
    ERROR = 5,
} LogLevel;

/**
 * 日志消息的日志颜色。
 */
typedef enum LogColor {
    /**
     * 默认/常规的日志颜色。
     */
    NORMAL = 0,
    /**
     * 绿色日志颜色，通常用于 [`LogLevel::Info`] 日志级别，并与成功事件相关联。
     */
    GREEN = 1,
    /**
     * 蓝色日志颜色，通常用于 [`LogLevel::Info`] 日志级别，并与用户操作相关联。
     */
    BLUE = 2,
    /**
     * 品红色日志颜色，通常用于 [`LogLevel::Info`] 日志级别。
     */
    MAGENTA = 3,
    /**
     * 青色日志颜色，通常用于 [`LogLevel::Info`] 日志级别。
     */
    CYAN = 4,
    /**
     * 黄色日志颜色，通常用于 [`LogLevel::Warning`] 日志级别。
     */
    YELLOW = 5,
    /**
     * 红色日志颜色，通常用于 [`LogLevel::Error`] 级别。
     */
    RED = 6,
} LogColor;

/**
 * A real-time clock which uses system time.
 *
 * Timestamps are guaranteed to be unique and monotonically increasing.
 *
 * # Threading
 *
 * The clock holds thread-local runtime state and must remain on its originating thread.
 */
typedef struct LiveClock LiveClock;

/**
 * A guard that manages the lifecycle of the logging subsystem.
 *
 * `LogGuard` ensures the logging thread remains active while instances exist and properly
 * terminates when all guards are dropped. The system uses reference counting to track active
 * guards - when the last `LogGuard` is dropped, the logging thread is joined to ensure all
 * pending log messages are written before the process terminates.
 *
 * # Reference Counting
 *
 * The logging system maintains a global atomic counter of active `LogGuard` instances. This
 * ensures that:
 * - The logging thread remains active as long as at least one `LogGuard` exists.
 * - All log messages are properly flushed when intermediate guards are dropped.
 * - The logging thread is cleanly terminated and joined when the last guard is dropped.
 *
 * # Shutdown Behavior
 *
 * When the last guard is dropped, the logging thread is signaled to close, drains pending
 * messages, and is joined to ensure all logs are written before process termination.
 *
 * **Python on Windows:** Non-deterministic GC order during interpreter shutdown can
 * occasionally prevent proper thread join, resulting in truncated logs.
 *
 * # Limits
 *
 * The system supports a maximum of 255 concurrent `LogGuard` instances.
 */
typedef struct LogGuard LogGuard;

/**
 * 一个静态测试时钟。
 *
 * 在内部存储当前时间戳，并且可以推进该时间。
 *
 * # 线程安全 (Threading)
 *
 * 此时钟是线程相关的 (thread-affine)；仅在创建它的线程中使用。
 */
typedef struct TestClock TestClock;

/**
 * C compatible Foreign Function Interface (FFI) for an underlying [`TestClock`].
 *
 * This struct wraps `TestClock` in a way that makes it compatible with C function
 * calls, enabling interaction with `TestClock` in a C environment.
 *
 * It implements the `Deref` trait, allowing instances of `TestClock_API` to be
 * dereferenced to `TestClock`, providing access to `TestClock`'s methods without
 * having to manually access the underlying `TestClock` instance.
 */
typedef struct TestClock_API {
    struct TestClock *_0;
} TestClock_API;

/**
 * C compatible Foreign Function Interface (FFI) for an underlying [`LiveClock`].
 *
 * This struct wraps `LiveClock` in a way that makes it compatible with C function
 * calls, enabling interaction with `LiveClock` in a C environment.
 *
 * It implements the `Deref` and `DerefMut` traits, allowing instances of `LiveClock_API` to be
 * dereferenced to `LiveClock`, providing access to `LiveClock`'s methods without
 * having to manually access the underlying `LiveClock` instance. This includes
 * both mutable and immutable access.
 */
typedef struct LiveClock_API {
    struct LiveClock *_0;
} LiveClock_API;

/**
 * C compatible Foreign Function Interface (FFI) for an underlying [`LogGuard`].
 *
 * This struct wraps `LogGuard` in a way that makes it compatible with C function
 * calls, enabling interaction with `LogGuard` in a C environment.
 *
 * It implements the `Deref` trait, allowing instances of `LogGuard_API` to be
 * dereferenced to `LogGuard`, providing access to `LogGuard`'s methods without
 * having to manually access the underlying `LogGuard` instance.
 */
typedef struct LogGuard_API {
    struct LogGuard *_0;
} LogGuard_API;

/**
 * 表示在事件时间戳处发生的一个时间事件 (Time Event)。
 *
 * 一个 `TimeEvent` 携带元数据，如事件名称、唯一的事件 ID，
 * 以及指明事件计划发生时间和初始化时间的时间戳。
 */
typedef struct TimeEvent_t {
    /**
     * 事件名称，标识事件的性质或目的。
     */
    char* name;
    /**
     * 事件的唯一标识符。
     */
    UUID4_t event_id;
    /**
     * 事件发生时的 UNIX 时间戳（纳秒）。
     */
    uint64_t ts_event;
    /**
     * 实例创建时的 UNIX 时间戳（纳秒）。
     */
    uint64_t ts_init;
} TimeEvent_t;

/**
 * FFI time event handler for Cython interoperability.
 *
 * Associates a `TimeEvent` with a callback function that is triggered
 * when the event's timestamp is reached.
 */
typedef struct TimeEventHandler_t {
    /**
     * The time event.
     */
    struct TimeEvent_t event;
    /**
     * The callable raw pointer.
     */
    char *callback_ptr;
} TimeEventHandler_t;

/**
 * Match a topic and a string pattern using iterative backtracking algorithm
 * pattern can contains -
 * '*' - match 0 or more characters after this
 * '?' - match any character once
 * 'a-z' - match the specific character
 *
 * # Safety
 *
 * Passing `NULL` pointers will result in a panic.
 */
uint8_t is_matching_ffi(const char *topic, const char *pattern);

struct TestClock_API test_clock_new(void);

void test_clock_drop(struct TestClock_API clock);

/**
 * Registers the default callback handler for TestClock.
 *
 * # Safety
 *
 * Assumes `callback_ptr` is a valid `PyCallable` pointer.
 *
 * # Panics
 *
 * Panics if the `callback_ptr` is null or represents the Python `None` object.
 */
void test_clock_register_default_handler(struct TestClock_API *clock, PyObject *callback_ptr);

void test_clock_set_time(const struct TestClock_API *clock, uint64_t to_time_ns);

double test_clock_timestamp(const struct TestClock_API *clock);

uint64_t test_clock_timestamp_ms(const struct TestClock_API *clock);

uint64_t test_clock_timestamp_us(const struct TestClock_API *clock);

uint64_t test_clock_timestamp_ns(const struct TestClock_API *clock);

const char *test_clock_timer_names(const struct TestClock_API *clock);

uintptr_t test_clock_timer_count(struct TestClock_API *clock);

/**
 * # Safety
 *
 * This function assumes:
 * - `name_ptr` is a valid C string pointer.
 * - `callback_ptr` is a valid `PyCallable` pointer.
 *
 * # Panics
 *
 * Panics if `callback_ptr` is null or if setting the timer fails.
 */
void test_clock_set_time_alert(struct TestClock_API *clock,
                               const char *name_ptr,
                               uint64_t alert_time_ns,
                               PyObject *callback_ptr,
                               uint8_t allow_past);

/**
 * # Safety
 *
 * This function assumes:
 * - `name_ptr` is a valid C string pointer.
 * - `callback_ptr` is a valid `PyCallable` pointer.
 *
 * # Parameters
 *
 * - `start_time_ns`: UNIX timestamp in nanoseconds. Use `0` to indicate "use current time".
 * - `stop_time_ns`: UNIX timestamp in nanoseconds. Use `0` to indicate "no stop time".
 *
 * # Panics
 *
 * Panics if `callback_ptr` is null or represents the Python `None` object.
 */
void test_clock_set_timer(struct TestClock_API *clock,
                          const char *name_ptr,
                          uint64_t interval_ns,
                          uint64_t start_time_ns,
                          uint64_t stop_time_ns,
                          PyObject *callback_ptr,
                          uint8_t allow_past,
                          uint8_t fire_immediately);

/**
 * # Safety
 *
 * Assumes `set_time` is a correct `uint8_t` of either 0 or 1.
 */
CVec test_clock_advance_time(struct TestClock_API *clock, uint64_t to_time_ns, uint8_t set_time);

/**
 * Drops a `CVec` of `TimeEventHandler_API` values.
 *
 * # Panics
 *
 * Panics if `CVec` invariants are violated (corrupted metadata).
 */
void vec_time_event_handlers_drop(CVec v);

/**
 * # Safety
 *
 * Assumes `name_ptr` is a valid C string pointer.
 */
uint64_t test_clock_next_time(struct TestClock_API *clock, const char *name_ptr);

/**
 * # Safety
 *
 * Assumes `name_ptr` is a valid C string pointer.
 */
void test_clock_cancel_timer(struct TestClock_API *clock, const char *name_ptr);

void test_clock_cancel_timers(struct TestClock_API *clock);

struct LiveClock_API live_clock_new(void);

void live_clock_drop(struct LiveClock_API clock);

/**
 * # Safety
 *
 * Assumes `callback_ptr` is a valid `PyCallable` pointer.
 *
 * # Panics
 *
 * Panics if `callback_ptr` is null or represents the Python `None` object.
 */
void live_clock_register_default_handler(struct LiveClock_API *clock, PyObject *callback_ptr);

double live_clock_timestamp(struct LiveClock_API *clock);

uint64_t live_clock_timestamp_ms(struct LiveClock_API *clock);

uint64_t live_clock_timestamp_us(struct LiveClock_API *clock);

uint64_t live_clock_timestamp_ns(struct LiveClock_API *clock);

const char *live_clock_timer_names(const struct LiveClock_API *clock);

uintptr_t live_clock_timer_count(struct LiveClock_API *clock);

/**
 * # Safety
 *
 * This function assumes:
 * - `name_ptr` is a valid C string pointer.
 * - `callback_ptr` is a valid `PyCallable` pointer.
 *
 * # Panics
 *
 * This function panics if:
 * - `name` is not a valid string.
 * - `callback_ptr` is NULL and no default callback has been assigned on the clock.
 */
void live_clock_set_time_alert(struct LiveClock_API *clock,
                               const char *name_ptr,
                               uint64_t alert_time_ns,
                               PyObject *callback_ptr,
                               uint8_t allow_past);

/**
 * # Safety
 *
 * This function assumes:
 * - `name_ptr` is a valid C string pointer.
 * - `callback_ptr` is a valid `PyCallable` pointer.
 *
 * # Parameters
 *
 * - `start_time_ns`: UNIX timestamp in nanoseconds. Use `0` to indicate "use current time".
 * - `stop_time_ns`: UNIX timestamp in nanoseconds. Use `0` to indicate "no stop time".
 *
 * # Panics
 *
 * This function panics if:
 * - `name` is not a valid string.
 * - `callback_ptr` is NULL and no default callback has been assigned on the clock.
 */
void live_clock_set_timer(struct LiveClock_API *clock,
                          const char *name_ptr,
                          uint64_t interval_ns,
                          uint64_t start_time_ns,
                          uint64_t stop_time_ns,
                          PyObject *callback_ptr,
                          uint8_t allow_past,
                          uint8_t fire_immediately);

/**
 * # Safety
 *
 * Assumes `name_ptr` is a valid C string pointer.
 */
uint64_t live_clock_next_time(struct LiveClock_API *clock, const char *name_ptr);

/**
 * # Safety
 *
 * Assumes `name_ptr` is a valid C string pointer.
 */
void live_clock_cancel_timer(struct LiveClock_API *clock, const char *name_ptr);

void live_clock_cancel_timers(struct LiveClock_API *clock);

const char *component_state_to_cstr(enum ComponentState value);

/**
 * Returns an enum from a Python string.
 *
 * # Safety
 *
 * Assumes `ptr` is a valid C string pointer.
 *
 * # Panics
 *
 * Panics if the input C string does not match a valid enum variant.
 */
enum ComponentState component_state_from_cstr(const char *ptr);

const char *component_trigger_to_cstr(enum ComponentTrigger value);

/**
 * Returns an enum from a Python string.
 *
 * # Safety
 *
 * Assumes `ptr` is a valid C string pointer.
 *
 * # Panics
 *
 * Panics if the input C string does not match a valid enum variant.
 */
enum ComponentTrigger component_trigger_from_cstr(const char *ptr);

const char *log_level_to_cstr(enum LogLevel value);

/**
 * Returns an enum from a Python string.
 *
 * # Safety
 *
 * Assumes `ptr` is a valid C string pointer.
 *
 * # Panics
 *
 * Panics if the input C string does not match a valid enum variant.
 */
enum LogLevel log_level_from_cstr(const char *ptr);

const char *log_color_to_cstr(enum LogColor value);

/**
 * Returns an enum from a Python string.
 *
 * # Safety
 *
 * Assumes `ptr` is a valid C string pointer.
 *
 * # Panics
 *
 * Panics if the input C string does not match a valid enum variant.
 */
enum LogColor log_color_from_cstr(const char *ptr);

/**
 * Initializes logging.
 *
 * Logging should be used for Python and sync Rust logic which is most of
 * the components in the [nautilus_trader](https://pypi.org/project/nautilus_trader) package.
 * Logging can be configured to filter components and write up to a specific level only
 * by passing a configuration using the `NAUTILUS_LOG` environment variable.
 *
 * # Safety
 *
 * Should only be called once during an application's run, ideally at the
 * beginning of the run.
 *
 * This function assumes:
 * - `directory_ptr` is either NULL or a valid C string pointer.
 * - `file_name_ptr` is either NULL or a valid C string pointer.
 * - `file_format_ptr` is either NULL or a valid C string pointer.
 * - `component_level_ptr` is either NULL or a valid C string pointer.
 *
 * # Panics
 *
 * Panics if initializing the Rust logger fails.
 */
struct LogGuard_API logging_init(TraderId_t trader_id,
                                 UUID4_t instance_id,
                                 enum LogLevel level_stdout,
                                 enum LogLevel level_file,
                                 const char *directory_ptr,
                                 const char *file_name_ptr,
                                 const char *file_format_ptr,
                                 const char *component_levels_ptr,
                                 uint8_t is_colored,
                                 uint8_t is_bypassed,
                                 uint8_t print_config,
                                 uint8_t log_components_only,
                                 uint64_t max_file_size,
                                 uint32_t max_backup_count);

/**
 * Creates a new log event.
 *
 * # Safety
 *
 * This function assumes:
 * - `component_ptr` is a valid C string pointer.
 * - `message_ptr` is a valid C string pointer.
 */
void logger_log(enum LogLevel level,
                enum LogColor color,
                const char *component_ptr,
                const char *message_ptr);

/**
 * Logs the Nautilus system header.
 *
 * # Safety
 *
 * This function assumes:
 * - `machine_id_ptr` is a valid C string pointer.
 * - `component_ptr` is a valid C string pointer.
 */
void logging_log_header(TraderId_t trader_id,
                        const char *machine_id_ptr,
                        UUID4_t instance_id,
                        const char *component_ptr);

/**
 * Logs system information.
 *
 * # Safety
 *
 * Assumes `component_ptr` is a valid C string pointer.
 */
void logging_log_sysinfo(const char *component_ptr);

/**
 * Flushes global logger buffers of any records.
 */
void logger_flush(void);

/**
 * Flushes global logger buffers of any records and then drops the logger.
 */
void logger_drop(struct LogGuard_API log_guard);

uint8_t logging_is_initialized(void);

void logging_set_bypass(void);

void logging_shutdown(void);

uint8_t logging_is_colored(void);

void logging_clock_set_realtime_mode(void);

void logging_clock_set_static_mode(void);

void logging_clock_set_static_time(uint64_t time_ns);

/**
 * Drops a `TimeEventHandler_API`, releasing any Python callback reference.
 *
 * # Safety
 *
 * The handler must be valid and not previously dropped.
 */
void time_event_handler_drop(struct TimeEventHandler_t handler);

/**
 * # Safety
 *
 * Assumes `name_ptr` is borrowed from a valid Python UTF-8 `str`.
 */
struct TimeEvent_t time_event_new(const char *name_ptr,
                                  UUID4_t event_id,
                                  uint64_t ts_event,
                                  uint64_t ts_init);

/**
 * Returns a [`TimeEvent`] as a C string pointer.
 */
const char *time_event_to_cstr(const struct TimeEvent_t *event);

struct TimeEventHandler_t dummy(struct TimeEventHandler_t v);
