/* Generated with cbindgen:0.29.2 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdint.h>
#include <Python.h>

/**
 * 一秒包含的毫秒数。
 */
#define MILLISECONDS_IN_SECOND 1000

/**
 * 一秒包含的纳秒数。
 */
#define NANOSECONDS_IN_SECOND 1000000000

/**
 * 一毫秒包含的纳秒数。
 */
#define NANOSECONDS_IN_MILLISECOND 1000000

/**
 * 一微秒包含的纳秒数。
 */
#define NANOSECONDS_IN_MICROSECOND 1000

/**
 * [`StackStr`] 的最大字符容量。
 */
#define STACKSTR_CAPACITY 36

/**
 * `CVec` 是一个 C 兼容的结构体，存储指向内存块的一个不透明指针，
 * 及其长度和分配该向量时的容量。
 *
 * # 安全性 (Safety)
 *
 * 更改此处的数值可能会导致在销毁内存时产生未定义行为。
 */
typedef struct CVec {
    /**
     * 指向存放元素内存块的不透明指针。若要访问元素，需将其转换为底层类型。
     */
    void *ptr;
    /**
     * 块中元素的数量。
     */
    uintptr_t len;
    /**
     * 分配该向量时的容量。
     * 在解除内存分配时使用。
     */
    uintptr_t cap;
} CVec;

/**
 * 表示根据 RFC 4122 规范基于 128 位标签生成的
 * 版本 4 通用唯一识别码 (UUID)。
 */
typedef struct UUID4_t {
    /**
     * 作为固定长度 C 字符串字节数组存储的 UUID v4 值（包含 null 终止符）。
     */
    uint8_t value[37];
} UUID4_t;

/**
 * 一种栈分配的 ASCII 字符串，最大容量为 36 个字符。
 *
 * 针对短标识符字符串进行了以下优化：
 * - 栈分配（无堆分配）。
 * - `Copy` 语义。
 * - O(1) 时间复杂度的长度访问。
 * - C FFI 兼容性（以 null 结尾）。
 *
 * 要求 ASCII 是为了保证 1 个字符等于 1 个字节，确保缓冲区始终能够容纳刚好其容量大小的字符数。
 * 这与标识符通常本质上是 ASCII 的惯例相吻合。
 *
 * # 内存布局
 *
 * `value` 字段被放置在最前面，因此结构体指针等于字符串指针，
 * 使得 C FFI 更加自然：`(char*)&stack_str` 可以直接工作。
 */
typedef struct StackStr {
    /**
     * 带有 null 终止符的 ASCII 数据，用于 C FFI。
     */
    uint8_t value[37];
    /**
     * 字符串的字节长度 (0-36)。
     */
    uint8_t len;
} StackStr;
/**
 * 最大字符长度。
 */
#define StackStr_MAX_LEN STACKSTR_CAPACITY

/**
 * 构造一个新的*空* [`CVec`] 值，用作外部代码中的初始化程序或哨兵。
 */
struct CVec cvec_new(void);

/**
 * 将 UNIX 纳秒时间戳转换为 ISO 8601 (RFC 3339) 格式的 C 字符串指针。
 */
const char *unix_nanos_to_iso8601_cstr(uint64_t timestamp_ns);

/**
 * 将 UNIX 纳秒时间戳转换为带毫秒精度的 ISO 8601 (RFC 3339) 格式的 C 字符串指针。
 */
const char *unix_nanos_to_iso8601_millis_cstr(uint64_t timestamp_ns);

/**
 * 将秒 (s) 转换为纳秒 (ns)。
 */
uint64_t secs_to_nanos(double secs);

/**
 * 将秒 (s) 转换为毫秒 (ms)。
 */
uint64_t secs_to_millis(double secs);

/**
 * 将毫秒 (ms) 转换为纳秒 (ns)。
 */
uint64_t millis_to_nanos(double millis);

/**
 * 将微秒 (μs) 转换为纳秒 (ns)。
 */
uint64_t micros_to_nanos(double micros);

/**
 * 将纳秒 (ns) 转换为秒 (s)。
 */
double nanos_to_secs(uint64_t nanos);

/**
 * 将纳秒 (ns) 转换为毫秒 (ms)。
 */
uint64_t nanos_to_millis(uint64_t nanos);

/**
 * 将纳秒 (ns) 转换为微秒 (μs)。
 */
uint64_t nanos_to_micros(uint64_t nanos);

/**
 * 返回从给定 C 字符串推断出的十进制精度。
 *
 * # 安全性 (Safety)
 *
 * 假定 `ptr` 是一个有效的 C 字符串指针。
 *
 * # Panics
 *
 * 如果 `ptr` 为空，则触发 panic。
 */
uint8_t precision_from_cstr(const char *ptr);

/**
 * 返回从给定 C 字符串推断出的最小价格增量的十进制精度。
 *
 * # 安全性 (Safety)
 *
 * 假定 `ptr` 是一个有效的 C 字符串指针。
 *
 * # Panics
 *
 * 如果 `ptr` 为空，则触发 panic。
 */
uint8_t min_increment_precision_from_cstr(const char *ptr);

/**
 * 释放指针指向的 C 字符串内存。
 *
 * # 安全性 (Safety)
 *
 * 假定 `ptr` 是一个有效的 C 字符串指针。
 *
 * # Panics
 *
 * 如果 `ptr` 为空，则触发 panic。
 */
void cstr_drop(const char *ptr);

/**
 * 生成一个新的随机（版本 4）UUID 并在返回值中返回。
 */
struct UUID4_t uuid4_new(void);

/**
 * 从 C 字符串指针返回一个 [`UUID4`]。
 *
 * # 安全性 (Safety)
 *
 * 假定 `ptr` 是一个有效的 C 字符串指针。
 *
 * # Panics
 *
 * 如果 `ptr` 无法被转换为有效的 C 字符串，则触发 panic。
 */
struct UUID4_t uuid4_from_cstr(const char *ptr);

/**
 * 返回一个借用的、*以 null 结尾的* 表示 `uuid` 的 UTF-8 C 字符串。
 *
 * 该指针的有效性与输入的 `UUID4` 引用所具有的生命周期相同 —— 调用方**不得**尝试释放它。
 */
const char *uuid4_to_cstr(const struct UUID4_t *uuid);

/**
 * 比较两个 UUID 值。相等时返回 `1`，否则返回 `0`。
 */
uint8_t uuid4_eq(const struct UUID4_t *lhs, const struct UUID4_t *rhs);

/**
 * 使用 Rust 的默认哈希器计算 `uuid` 稳定的 [`u64`] 哈希值。
 */
uint64_t uuid4_hash(const struct UUID4_t *uuid);
